name: Vault
description: Use the Github Action
inputs:
  vault_secret_id:
    description: Test input.
    required: false

runs:
  using: composite
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: pip install -r $GITHUB_ACTION_PATH/../src/requirements.txt 
      shell: bash

    - name: Pass Inputs to Shell
      run: |
          echo "INPUT_API_TOKEN=TOKEN_TEST" >> $GITHUB_ENV
          echo "VAULT_URL=https://hero-labs-public-vault-52027e0c.ba335454.z1.hashicorp.cloud:8200" >> $GITHUB_ENV
          echo "VAULT_NAMESPACE=admin" >> $GITHUB_ENV
          echo "VAULT_ROLE_ID=110063fe-4433-1227-6ac2-291fc924e688" >> $GITHUB_ENV 
          echo "VAULT_SECRET_ID=${{ inputs.vault_secret_id }}" >> $GITHUB_ENV
          echo "SECRET_BASE_PATH=staging/iot" >> $GITHUB_ENV
      shell: bash

    - name: Fetch the Shipyard environment variables
      id: secrets
      run: |
        # echo "$(python $GITHUB_ACTION_PATH/../src/main.py)" >> $GITHUB_OUTPUT 
        echo "KEY1=VALUE1" >> $GITHUB_OUTPUT 
        echo "KEY2=VALUE2" >> $GITHUB_OUTPUT 
      shell: bash

    - name: Output
      shell: bash
      run: |
         echo ${{join(steps.secrets.outputs.*, '\n')}}
  
  
        #  echo "${{steps.abc.outputs.FAV_NUMBER}}"

# ${{join(steps.run_tests.outputs.*, '\n')}}
    # - name: Install Dependencies
    #   run: pip install -r $GITHUB_ACTION_PATH/../src/requirements.txt > /dev/null
    #   shell: bash

    #   # Pass inputs via shell until https://github.com/actions/runner/issues/665 resolved
    # - name: Pass Inputs to Shell
    #   run: |
    #       echo "INPUT_API_TOKEN=${{ inputs.api-token }}" >> $GITHUB_ENV
    #       echo "INPUT_TIMEOUT_MINUTES=${{ inputs.timeout-minutes }}" >> $GITHUB_ENV
    #       echo "INPUT_APP_NAME=${{ inputs.app-name }}" >> $GITHUB_ENV
    #   shell: bash
    # - name: Fetch the Shipyard environment variables
    #   run: python $GITHUB_ACTION_PATH/../src/fetch_shipyard_env.py 
    #   shell: bash

