name: Vault
description: Use the Github Action
inputs:
  name:
    description: Test input.
    required: false

runs:
  using: composite
  steps:
    - name: Install Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Debug message
      run: |
        echo "Hello!"
      shell: bash

    - name: Install Dependencies
      run: pip install -r $GITHUB_ACTION_PATH/../src/requirements.txt 
      shell: bash

    - name: Pass Inputs to Shell
      run: |
          echo "INPUT_API_TOKEN=TOKEN_TEST" >> $GITHUB_ENV
      shell: bash

    - name: Fetch the Shipyard environment variables
      run: python $GITHUB_ACTION_PATH/../src/main.py 
      shell: bash

    # - name: Install Dependencies
    #   run: pip install -r $GITHUB_ACTION_PATH/../src/requirements.txt > /dev/null
    #   shell: bash

    #   # Pass inputs via shell until https://github.com/actions/runner/issues/665 resolved
    # - name: Pass Inputs to Shell
    #   run: |
    #       echo "INPUT_API_TOKEN=${{ inputs.api-token }}" >> $GITHUB_ENV
    #       echo "INPUT_TIMEOUT_MINUTES=${{ inputs.timeout-minutes }}" >> $GITHUB_ENV
    #       echo "INPUT_APP_NAME=${{ inputs.app-name }}" >> $GITHUB_ENV
    #   shell: bash
    # - name: Fetch the Shipyard environment variables
    #   run: python $GITHUB_ACTION_PATH/../src/fetch_shipyard_env.py 
    #   shell: bash

