---
name: "secrets"

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  pre-release:
    name: "test"
    runs-on: "ubuntu-latest"

    steps:
      # ...
      - name: "Build & test"
        run: |
          echo "done!"
      
      - uses: "ikscream/python-github-action-vault/vault@main"
        with:
          vault_secret_id: ${{ secrets.VAULT_SECRET_ID }}